# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
      - dev

pr:
  branches:
    include:
      - dev

pool:
  vmImage: 'Ubuntu-16.04' 

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  proj-dir: "src"
  imageTag: ''

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  enabled: true

- task: UseDotNet@2
  displayName: 'Set pipeline to use DotNet Core 3.1'
  inputs:
    version: '3.1.x'
    includePreviewVersions: false
  enabled: true

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for project'
  inputs:
    restoreSolution: '$(proj-dir)/MedPark.Payment.csproj'
  enabled: true

- task: CmdLine@2
  displayName: 'Install Dotnet Tools'
  inputs:
    script: 'dotnet tool install --global dotnet-ef'
  enabled: true

- task: CmdLine@2
  displayName: 'Generate DB migration script for MedPark.Payment'
  inputs:
    script: 'dotnet ef migrations script --project $(proj-dir)/MedPark.Payment.csproj -i -o $(build.artifactstagingdirectory)/sql/MedPark.Payment_DB_Migrations.sql'
  enabled: true

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(proj-dir)/MedPark.Payment.csproj'
    arguments: '-c Release'
  enabled: false

- task: Docker@2
  displayName: 'Login to Docker Hub'
  condition: and(succeeded(), or(eq(variables['build.SourceBranch'], 'refs/heads/dev'), eq(variables['build.SourceBranch'], 'refs/heads/master')))
  inputs:
    containerRegistry: 'docker-hub-connection'
    command: 'login'
  enabled: true

- powershell: |
    $currentBranch = "$(build.SourceBranch)"
    Write-Host "Current Branch is: $currentBranch"

    if ($currentBranch -eq 'refs/heads/master') {
      Write-Host ##vso[task.setvariable variable=imageTag;isOutput=true]latest
      Write-Host "New tag - $env:imageTag"
    } else {
      Write-Host "Current Branch is dev/feature"
      Write-Host ##vso[task.setvariable variable=imageTag]dev
    }
  displayName: 'Set Docker image tag based on branch'
  condition: and(succeeded(), or(eq(variables['build.SourceBranch'], 'refs/heads/dev'), eq(variables['build.SourceBranch'], 'refs/heads/master')))
  enabled: true

- task: Docker@2
  displayName: 'Build and Push docker image'
  condition: and(succeeded(), or(eq(variables['build.SourceBranch'], 'refs/heads/dev'), eq(variables['build.SourceBranch'], 'refs/heads/master')))
  inputs:
    containerRegistry: 'docker-hub-connection'
    repository: 'geradedev/medpark-payment'
    command: 'buildAndPush'
    Dockerfile: '$(proj-dir)/Dockerfile.multistage'
    tags: $(imageTag)
  enabled: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  enabled: true
